spring.application.name=bankservice

server.port = 8080
spring.datasource.url=jdbc:mysql://localhost:3306/bank_service
spring.datasource.username=root
spring.datasource.password=mysql
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
jwt.secret=kN4GqKA1LrQUqZO11QSj/lOlMK4XIGJYX4dnM/eFG4kEIdREaqyP9EnUz58RW5rn7cZhR7RlhsZqwPwX+JeNlQ==